channels:
  - defaults
  - conda-forge
dependencies:
  - numpy=1.20.1
  - pip=21.0.1
  - python=3.9
  - natsort>=8.2.0
  - pandas=1.4
  - matplotlib==3.4.3
  - scipy>=1.8
  - seaborn>=0.12
  - cmocean==2.0
  - astropy
#  - pickle=4.0
  - corner

#  Bioverse requires a few packages:
  - dynesty=1.1
  - emcee=3.1.1

# install Bioverse:
  - pip:
    - git+https://github.com/danielapai/bioverse@v1.1.1
#    - -e /Users/schlecker/repos/bioverse