channels:
  - defaults
  - conda-forge
dependencies:
  - numpy=1.20.1
  - pip=21.0.1
  - python=3.9
  - natsort>=8.2.0
  - pandas=1.4
  - matplotlib>=3.5
  - scipy>=1.8
  - seaborn>=0.12
  - cmocean>=2.0
  - astropy
#  - pickle=4.0

# install Bioverse version 1.1.0:
  - pip:
    - git+https://github.com/danielapai/bioverse@v1.1.0
#    - -e /Users/schlecker/repos/bioverse